export enum Ville {
    SOUSSE = "Sousse",
    MONASTIR = "Monastir",
    MAHDIA = "Mahdia",
    SFAX = "Sfax",
    NABEUL = "Nabeul",
    BIZERTE = "Bizerte",
    TUNIS = "Tunis",
    ARIANA = "Ariana",
    MANOUBA = "Manouba",
    BEN_AROUS = "Ben Arous",
    KAIROUAN = "Kairouan",
    GABES = "Gabès",
    GAFSA = "Gafsa",    
    TATAOUINE = "Tataouine",
    MEDENINE = "Médenine",
    TOZEUR = "Tozeur",
    KEBILI = "Kébili",
    BEJA = "Béja",
    JENDOUBA = "Jendouba",
    KEF = "Le Kef",
    SILIANA = "Siliana",
    ZAGHOUAN = "Zaghouan",
    KASSERINE = "Kasserine",
    SIDI_BOUZID = "Sidi Bouzid",
  }